// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUzfBd7I6e2okuSOlcp8bVLQfIMMTwmgs',
    appId: '1:289656585073:web:9f8ecd0e7e24110db9d4d0',
    messagingSenderId: '289656585073',
    projectId: 'koscash-f14ba',
    authDomain: 'koscash-f14ba.firebaseapp.com',
    storageBucket: 'koscash-f14ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh6nUNKhuWhHlnwnyy7jJpFqPC9AMnoCI',
    appId: '1:289656585073:android:ff1cf69f1dfe5798b9d4d0',
    messagingSenderId: '289656585073',
    projectId: 'koscash-f14ba',
    storageBucket: 'koscash-f14ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxdq7MqQbb6lIIynaEl9hAtCmq8gXyoxE',
    appId: '1:289656585073:ios:9e1eddeb823c8484b9d4d0',
    messagingSenderId: '289656585073',
    projectId: 'koscash-f14ba',
    storageBucket: 'koscash-f14ba.firebasestorage.app',
    iosBundleId: 'com.example.koscash.koscash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxdq7MqQbb6lIIynaEl9hAtCmq8gXyoxE',
    appId: '1:289656585073:ios:9e1eddeb823c8484b9d4d0',
    messagingSenderId: '289656585073',
    projectId: 'koscash-f14ba',
    storageBucket: 'koscash-f14ba.firebasestorage.app',
    iosBundleId: 'com.example.koscash.koscash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUzfBd7I6e2okuSOlcp8bVLQfIMMTwmgs',
    appId: '1:289656585073:web:990b65363ff34158b9d4d0',
    messagingSenderId: '289656585073',
    projectId: 'koscash-f14ba',
    authDomain: 'koscash-f14ba.firebaseapp.com',
    storageBucket: 'koscash-f14ba.firebasestorage.app',
  );
}
